### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by igor-stoppa**
1) Add support for EXT interrupts on ATMega328P (Arduino UNO)
2) Add support for PC interrupts on ATMega328P (Arduino UNO)
3) Adjust the example accordingly
4) Optimize creation of binary executable by dropping unused portions.

### CODE REVIEW

**Comment by marcoveeneman** [comment]
I think the PC driver is not really needed. As I understand you created the PC driver because some pins don't have dedicated IRQ lines. This is not a problem since you can handle multiple pins in a single IRQ handler. For example the STM32 and Tiva ports have multiple pins sharing the same IRQ.

**Comment by igor-stoppa** [comment]
I created the PC driver because it's a separate IP block.
The same pins that can be used as EXT (with a dedicated IRQ line each) can also be used in PC mode.
But with a different circuitry behind.
Having a separate driver allows to have homogeneous handling (and timing), if so desired.
If I had grouped them together, it would have required adding extra defines to the ext_lld to differentiate the case where the application programmer wants to use such pins as EXT vs PC mode.
Btw, please have a look at the code, I am handling multiple pins in the same IRQ handler.
What makes you think otherwise?

**Comment by utzig** [comment]
The standard procedure for "special cases" is to add extra non-mandatory fields for the ext driver. You don't usually add a new subsystem for a specific processor if it will not be generalized to other MCU families. I'll review your code tonight.

**Comment by igor-stoppa** [comment]
Thanks for the review.
While you are at it, I'd have also a couple of questions:

- pad direction and pullup configuration: is this supposed to be done using the pal.h interface?

- there are macros that definestructures named PORTx where x is a number - why?
  To me it seems counter-intuitive, since all the ports on AVR are addressed with letters.
  And that's also how both the manual  and the schematics of any board refer to them.

**Comment by igor-stoppa** [comment]
I have a half idea of how to collapse the two drivers. I don't particularly like it, but if that's what it takes to get the functionality merged, so be it. If I get it to work, I'll send an updated pull request.

**Comment by utzig** [comment]
Two suggestions:

1) Don't modify the standard demo. Create a new demo for ext in /testhal/AVR/EXT.
2) Although the code in the pc_driver looks interesting I don't think it will ever be accepted to be merged. Just make a single EXT that supports both INT/PCINT options.

**Comment by igor-stoppa** [comment]
I'll close this and send a new PR

**Pull request closed without merging**
